#!/usr/bin/env python3
"""Bake the CIE tables the plugin carries into source/CieTables.h.

Inputs (not in this repo; the header records where they came from):

  1. The CIE 1931 2-degree colour matching functions at 1 nm, 360-830 nm, as the
     header `ciexyzCurves1931_1nm.h` from the supplemental repository of Wyman,
     Sloan and Shirley, "Simple Analytic Approximations to the CIE XYZ Color
     Matching Functions", JCGT 2(2) 2013
     (github.com/JournalOfComputerGraphicsTechniques/TEST-0002-02-01-Wyman-Sloan-Shirley,
     data/ciexyzCurves1931_1nm.h), which credits the RIT Munsell Color Science
     Laboratory's online CIE tables (cis.rit.edu/mcsl/online/cie.php).
  2. The CIE standard illuminant D65 relative spectral power distribution at 5 nm,
     300-780 nm, as tabulated in colour-science's
     `colour/colorimetry/datasets/illuminants/sds.py` ("D65"), which carries the
     CIE 15:2004 Table T.1 values.

Usage::

    tools/bake_cie.py ciexyzCurves1931_1nm.h sds.py > source/CieTables.h

The plugin integrates at 10 nm from 380 to 780 nm (41 samples), a Riemann sum.
The harness's `--spectra` and `--beer` references integrate the SAME 10 nm table
in double; the spectra being modelled are Gaussians tens of nm wide, so the
quadrature error of a 10 nm step is below a part in 10^4 of the result and is
the same on both sides. The tables are data, not a fit: nothing here is
approximated.
"""
import re
import sys


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    cmf_text = open(sys.argv[1]).read()
    rows = re.findall(r"\{\s*([0-9.eE+-]+)f,\s*([0-9.eE+-]+)f,\s*([0-9.eE+-]+)f\s*\},\s*//\s*(\d+) nm", cmf_text)
    cmf = {int(nm): (float(x), float(y), float(z)) for x, y, z, nm in rows}
    sds = open(sys.argv[2]).read()
    block = sds[sds.index('"D65": {'):]
    block = block[: block.index("},")]
    d65 = {int(k): float(v) for k, v in re.findall(r"(\d+):\s*([0-9.]+)", block)}

    lams = list(range(380, 781, 10))
    for lam in lams:
        if lam not in cmf or lam not in d65:
            sys.exit(f"missing {lam} nm")

    out = []
    out.append("// GENERATED by tools/bake_cie.py -- do not edit. See that script for the provenance.")
    out.append("#pragma once")
    out.append("")
    out.append("namespace honeydew::cie")
    out.append("{")
    out.append("/// The wavelength samples: 380 to 780 nm every 10 nm, a Riemann sum.")
    out.append("constexpr int kLambdaCount = %d;" % len(lams))
    out.append("constexpr double kLambda0  = 380.0;")
    out.append("constexpr double kLambdaStep = 10.0;")
    out.append("")
    out.append("/// CIE 1931 2-degree colour matching functions (xbar, ybar, zbar) at the samples.")
    out.append("/// Source: RIT MCSL CIE tables via the JCGT 2(2) 2013 supplemental repository.")
    out.append("constexpr double kXyzBar[kLambdaCount][3] = {")
    for lam in lams:
        x, y, z = cmf[lam]
        out.append("    { %.6f, %.6f, %.6f },// %d nm" % (x, y, z, lam))
    out.append("};")
    out.append("")
    out.append("/// CIE standard illuminant D65, relative spectral power, CIE 15:2004 Table T.1")
    out.append("/// (via colour-science's tabulation), at the samples.")
    out.append("constexpr double kD65[kLambdaCount] = {")
    line = "   "
    for i, lam in enumerate(lams):
        line += " %.4f," % d65[lam]
        if i % 6 == 5:
            out.append(line)
            line = "   "
    if line.strip():
        out.append(line)
    out.append("};")
    out.append("")
    out.append("} // namespace honeydew::cie")
    print("\n".join(out))


if __name__ == "__main__":
    main()
