/*
 * Stoatworks Labs - About window data for Honeydew.
 *
 * PROVISIONAL hand copy, adapted from a sibling (conway). In a released repo
 * this file is GENERATED by stoatworks-backend/scripts/sync-about.py from the
 * website's projects.json; until honeydew is registered there, this is the
 * one place the facts are written down. `guide` is empty: there is no user
 * guide yet, so the About block shows no User guide button (and the day it
 * does, the About block is last, so no control moves).
 */
#pragma once

namespace stoatworks::about
{
    inline constexpr auto name = "Honeydew";
    inline constexpr auto slug = "honeydew";
    inline constexpr auto hook = "Oscillating and clock reactions in a dish on a lightbox, for Resolume";
    inline constexpr auto licence = "MIT";
    inline constexpr auto guide = "";
    inline constexpr auto page = "https://stoatworks-labs.com/software/honeydew/";
    inline constexpr auto repo = "https://github.com/stoatworks-labs/honeydew";
    inline constexpr auto versionFallback = "v0.1.0";

    inline constexpr auto org = "Stoatworks Labs";
    inline constexpr auto home = "https://stoatworks-labs.com";
    inline constexpr auto tagline = "Open tools for the people who run the show.";

    /* The canonical funding links, matching FUNDING.yml and the support footer. */
    struct Link { const char* name; const char* url; };
    inline constexpr Link funding[] = {
        { "GitHub Sponsors", "https://github.com/sponsors/stoatworks-labs" },
        { "Ko-fi", "https://ko-fi.com/stoatworkslabs" },
        { "Patreon", "https://patreon.com/StoatworksLabs" },
        { "Liberapay", "https://liberapay.com/stoatworks-labs" },
    };
}
